# Rest of your configuration
title: 悟数学
description: "中学数学教材重构"
baseurl: "" # leave it empty unless your site is in a subfolder
url: "https://abdulle-sabaf.github.io" # your GitHub Pages URL
github_username: abdulle-sabaf
theme: "feeling-responsive" # This is the name of the theme you're using

# Settings for pagination, collections, etc.
paginate: 5